### ISSUE TITLE
SubmitFeed() fails with error message (Use of uninitialized value in subroutine ...)

### ISSUE THREAD

**Issue by ghost** [frodwith/Amazon-MWS#3]
With the newest version of the Amazon::MWS::Client class, I get an error message when calling SubmitFeed() with an XML message that goes into the HTTP body:

Use of uninitialized value in subroutine entry at Amazon/MWS/TypeMap.pm line 42.

I found out, that the cause is a call to the method to_amazon() in TypeMap.pm (this method is in line 42), which is being called with a type of 'HTTP-Body' which is not known in the mapping %to_map (the value is the request XML document).

By adding the type to the mapping, it seems to be resolved. The below patch should fix the problem. Would be great if you could have a look at it.

http://nopaste.info/78e8bf0820.html

**Comment by frodwith** [comment]
should be resolved in latest commit (though slightly differently than you suggested)
