### ISSUE TITLE
Call to SubmitFeed provides no result

### ISSUE THREAD

**Issue by ghost** [frodwith/Amazon-MWS#4]
When I do a SubmitFeed() call with a FeedType of '_POST_ORDER_FULFILLMENT_DATA_' (and a XML request document), I do not get a parsed result back (the response is just empty). Amazon sends a valid response XML document though. Doing some debugging, I found out that the problem seems to be in the line

return $spec->{respond}->($root);

in the method define_api_method(). Maybe you have an idea what could be wrong? An example Amazon MWS response can be found here:

http://nopaste.info/f1fdd46108.html

**Comment by ghost** [comment]
Seems like changing line 300 in Client.pm from

convert($root, SubmittedDate => 'datetime');

to

convert_FeedSubmissionInfo($root);

resolves the problem.

**Comment by frodwith** [comment]
Yo, I solved it slightly differently - since there will only ever be one FeedSubmissionInfo, using convert_FeedSubmissionInfo gives a slightly unintuitive response.  So I just grabbed that element from root in respond.  Anyways, latest commit should solve this.
